const express = require('express');
const router = express.Router();
const authController = require('../app/controllers/AuthController');
const homeController = require('../app/controllers/HomeController');
const auth = require('../app/middleware/auth');
const profileController = require('../app/controllers/ProfileController');
const uploadSingle = require('../config/uploadSingleFile');
const uploadMultiple = require('../config/uploadMultipleFile');
const encounterController = require('../app/controllers/EncounterController');

router.put('/profile/upload-avatar', auth, uploadSingle, profileController.uploadAvatar);
router.put('/profile/update-work-and-education', auth, profileController.updateWordAndEducation);
router.put('/profile/update-location', auth, profileController.updateLocation);
router.put('/profile/update-interests', auth, profileController.updateInterests);
router.put('/profile/update-language', auth, profileController.updateLanguage);
router.post('/register' , authController.register);
router.post('/login', authController.login);
router.post('/profile/upload-image', auth, uploadMultiple, profileController.uploadImage);
router.delete('/profile/remove-image/:_id', auth, profileController.removeImage);
router.get('/profile/set-avatar/:_id', auth, profileController.setAvatarbyId);
router.put('/profile/change-pass', auth, profileController.changePass);
router.put('/profile/update-basic-info', auth, profileController.updateBasicInfo);
router.put('/profile/update-contact', auth, profileController.updateContact);
router.put('/profile/change-status-contact/:_id', auth, profileController.changeStatusContact);
router.put('/profile/get-contact', auth, profileController.getContactByMemberId);
router.delete('/profile/delete', auth, profileController.delete);
router.put('/profile/update-personal-info', auth, profileController.updatePersonalInfo);
router.put('/profile/update-filter', auth, profileController.updateFilter);
router.get('/profile/get', auth, profileController.getMemberById);
router.get('/profile/get-member/:profileId', auth, profileController.getMemberByProfileId);
router.get('/search', auth, encounterController.search);
router.post('/encounter', auth, encounterController.get);
router.get('/get-spotlight', homeController.spotlight);
router.get('/', homeController.get);

module.exports = router;
